/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * File_GUI.java
 *
 * Created on Dec 11, 2013, 6:21:10 PM
 */
package FileAssignments;

import java.awt.Font;
import java.io.File;
import java.util.Date;

/**
 *
 * @author jayu
 */
public class File_GUI extends java.awt.Frame {

    File file;
    String URL;
    String type;

    /** Creates new form File_GUI */
    public File_GUI() {
        initComponents();
        setSize(680, 600);
        setLocationRelativeTo(null);
        textField2.setVisible(false);
        button3.setVisible(false);
        textField3.setVisible(false);
        label9.setVisible(false);
        textField3.setVisible(false);
        enableContents(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        label1 = new java.awt.Label();
        label2 = new java.awt.Label();
        textField1 = new java.awt.TextField();
        textArea1 = new java.awt.TextArea();
        button1 = new java.awt.Button();
        label3 = new java.awt.Label();
        label4 = new java.awt.Label();
        checkbox1 = new java.awt.Checkbox();
        checkbox2 = new java.awt.Checkbox();
        checkbox3 = new java.awt.Checkbox();
        checkbox4 = new java.awt.Checkbox();
        checkbox5 = new java.awt.Checkbox();
        button2 = new java.awt.Button();
        checkbox6 = new java.awt.Checkbox();
        label5 = new java.awt.Label();
        checkbox8 = new java.awt.Checkbox();
        label6 = new java.awt.Label();
        checkbox9 = new java.awt.Checkbox();
        checkbox10 = new java.awt.Checkbox();
        textField2 = new java.awt.TextField();
        button3 = new java.awt.Button();
        label9 = new java.awt.Label();
        label8 = new java.awt.Label();
        list1 = new java.awt.List();
        button4 = new java.awt.Button();
        textField3 = new java.awt.TextField();
        button5 = new java.awt.Button();
        label10 = new java.awt.Label();
        label7 = new java.awt.Label();

        setBackground(new java.awt.Color(204, 204, 255));
        setTitle("Operation On Files  By Jayesh Kabra(Indore Branch)");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                exitForm(evt);
            }
        });
        setLayout(null);

        label1.setAlignment(java.awt.Label.CENTER);
        label1.setFont(new java.awt.Font("Arial", 1, 24));
        label1.setForeground(new java.awt.Color(0, 0, 255));
        label1.setText("Operations on File");
        add(label1);
        label1.setBounds(130, 50, 400, 30);

        label2.setAlignment(java.awt.Label.CENTER);
        label2.setFont(new java.awt.Font("Arial", 1, 14));
        label2.setForeground(new java.awt.Color(0, 0, 255));
        label2.setText("Enter/paste the URL of file/directory");
        add(label2);
        label2.setBounds(200, 100, 260, 21);

        textField1.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        textField1.setText("D://");
        textField1.addTextListener(new java.awt.event.TextListener() {
            public void textValueChanged(java.awt.event.TextEvent evt) {
                textField1TextValueChanged(evt);
            }
        });
        textField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                textField1FocusLost(evt);
            }
        });
        add(textField1);
        textField1.setBounds(40, 140, 600, 30);

        textArea1.setEditable(false);
        add(textArea1);
        textArea1.setBounds(10, 240, 260, 210);

        button1.setFont(new java.awt.Font("Dialog", 1, 12));
        button1.setForeground(new java.awt.Color(0, 0, 255));
        button1.setLabel("Detail of URL");
        button1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button1ActionPerformed(evt);
            }
        });
        add(button1);
        button1.setBounds(247, 180, 160, 24);

        label3.setForeground(new java.awt.Color(255, 0, 0));
        add(label3);
        label3.setBounds(40, 180, 180, 20);

        label4.setFont(new java.awt.Font("Dialog", 1, 12));
        label4.setForeground(new java.awt.Color(0, 0, 255));
        label4.setText("Tick the change the  property of  given URL");
        add(label4);
        label4.setBounds(290, 300, 320, 20);

        checkbox1.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox1.setForeground(new java.awt.Color(0, 51, 255));
        checkbox1.setLabel("Parent");
        checkbox1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox1ItemStateChanged(evt);
            }
        });
        add(checkbox1);
        checkbox1.setBounds(290, 240, 60, 20);

        checkbox2.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox2.setForeground(new java.awt.Color(0, 51, 255));
        checkbox2.setLabel("Size");
        checkbox2.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox2ItemStateChanged(evt);
            }
        });
        add(checkbox2);
        checkbox2.setBounds(490, 270, 60, 20);

        checkbox3.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox3.setForeground(new java.awt.Color(0, 51, 255));
        checkbox3.setLabel("Last Modified");
        checkbox3.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox3ItemStateChanged(evt);
            }
        });
        add(checkbox3);
        checkbox3.setBounds(460, 240, 98, 20);

        checkbox4.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox4.setForeground(new java.awt.Color(0, 51, 255));
        checkbox4.setLabel("Can Be Read");
        checkbox4.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox4ItemStateChanged(evt);
            }
        });
        add(checkbox4);
        checkbox4.setBounds(390, 270, 100, 20);

        checkbox5.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox5.setForeground(new java.awt.Color(0, 51, 255));
        checkbox5.setLabel("Can be Write");
        checkbox5.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox5ItemStateChanged(evt);
            }
        });
        add(checkbox5);
        checkbox5.setBounds(290, 270, 100, 20);

        button2.setFont(new java.awt.Font("Dialog", 1, 12));
        button2.setForeground(new java.awt.Color(0, 0, 255));
        button2.setLabel("Clear");
        button2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2ActionPerformed(evt);
            }
        });
        add(button2);
        button2.setBounds(100, 210, 46, 24);

        checkbox6.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox6.setForeground(new java.awt.Color(0, 51, 255));
        checkbox6.setLabel("IsHidden");
        checkbox6.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox6ItemStateChanged(evt);
            }
        });
        add(checkbox6);
        checkbox6.setBounds(360, 240, 76, 20);

        label5.setFont(new java.awt.Font("Dialog", 1, 12));
        label5.setForeground(new java.awt.Color(0, 0, 255));
        label5.setText("Tick to display the following  property");
        add(label5);
        label5.setBounds(290, 220, 210, 20);

        checkbox8.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox8.setForeground(new java.awt.Color(0, 0, 255));
        checkbox8.setLabel("Readonly");
        checkbox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox8ItemStateChanged(evt);
            }
        });
        add(checkbox8);
        checkbox8.setBounds(290, 320, 80, 20);

        label6.setAlignment(java.awt.Label.CENTER);
        label6.setForeground(new java.awt.Color(51, 51, 255));
        label6.setText("(Indore Branch)");
        add(label6);
        label6.setBounds(480, 560, 130, 20);

        checkbox9.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox9.setForeground(new java.awt.Color(0, 0, 255));
        checkbox9.setLabel("Delete");
        checkbox9.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox9ItemStateChanged(evt);
            }
        });
        add(checkbox9);
        checkbox9.setBounds(370, 320, 60, 20);

        checkbox10.setFont(new java.awt.Font("Dialog", 2, 12));
        checkbox10.setForeground(new java.awt.Color(0, 0, 255));
        checkbox10.setLabel("Rename");
        checkbox10.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkbox10ItemStateChanged(evt);
            }
        });
        add(checkbox10);
        checkbox10.setBounds(290, 350, 70, 20);
        add(textField2);
        textField2.setBounds(370, 350, 90, 20);

        button3.setFont(new java.awt.Font("Dialog", 1, 12));
        button3.setForeground(new java.awt.Color(0, 0, 255));
        button3.setLabel("Update");
        button3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button3ActionPerformed(evt);
            }
        });
        add(button3);
        button3.setBounds(470, 350, 56, 24);

        label9.setFont(new java.awt.Font("Dialog", 2, 12));
        label9.setForeground(new java.awt.Color(0, 0, 255));
        label9.setText("Write extension");
        add(label9);
        label9.setBounds(440, 430, 100, 20);

        label8.setFont(new java.awt.Font("Dialog", 1, 12));
        label8.setForeground(new java.awt.Color(0, 0, 255));
        label8.setText("Search file with certain extension");
        add(label8);
        label8.setBounds(290, 380, 200, 20);

        list1.add(".txt");
        list1.add(".java");
        list1.add(".class");
        list1.add(".doc");
        list1.add(".png");
        list1.add(".jpg");
        list1.add("Custom");
        list1.setFont(new java.awt.Font("Dialog", 3, 12));
        list1.setForeground(new java.awt.Color(0, 0, 255));
        list1.setMultipleMode(true);
        list1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                list1ItemStateChanged(evt);
            }
        });
        add(list1);
        list1.setBounds(290, 400, 80, 60);

        button4.setFont(new java.awt.Font("Dialog", 1, 12));
        button4.setForeground(new java.awt.Color(0, 0, 255));
        button4.setLabel("Deselect");
        button4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button4ActionPerformed(evt);
            }
        });
        add(button4);
        button4.setBounds(460, 400, 66, 24);
        add(textField3);
        textField3.setBounds(430, 450, 120, 20);

        button5.setFont(new java.awt.Font("Dialog", 1, 12));
        button5.setForeground(new java.awt.Color(51, 51, 255));
        button5.setLabel("Search");
        button5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button5ActionPerformed(evt);
            }
        });
        add(button5);
        button5.setBounds(380, 400, 70, 24);

        label10.setAlignment(java.awt.Label.CENTER);
        label10.setFont(new java.awt.Font("Dialog", 1, 18));
        label10.setForeground(new java.awt.Color(51, 51, 255));
        label10.setText("Jayesh Kabra");
        add(label10);
        label10.setBounds(460, 530, 180, 28);

        label7.setForeground(new java.awt.Color(51, 51, 255));
        label7.setText("Developed By");
        add(label7);
        label7.setBounds(510, 510, 79, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /** Exit the Application */
    private void exitForm(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_exitForm
        System.exit(0);
    }//GEN-LAST:event_exitForm

    private void button1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button1ActionPerformed
        // TODO add your handling code here:
        URL = textField1.getText();
        file = new File(URL);
        type = "";
        Font bold = new Font("Dialog", 1, 12);
        if (file.exists()) {
            enableContents(true);
            if (file.isDirectory()) {
                type = "Directory";
            } else if (file.isFile()) {
                type = "File";
            }
            textArea1.setFont(bold);
            textArea1.setText("Given URL is for--> ");
            textArea1.append("\n" + type);
            textArea1.append("\nAbsolutePath-->");
            textArea1.append("\n" + file.getAbsolutePath());


        } else {
            enableContents(false);
            textArea1.setText("Searched query not found");
        }



    }//GEN-LAST:event_button1ActionPerformed

    private void textField1TextValueChanged(java.awt.event.TextEvent evt) {//GEN-FIRST:event_textField1TextValueChanged
        // TODO add your handling code here:
        if (textField1.getText().equals("")) {
            label3.setText("*Empty field found");
            button1.setEnabled(false);
        } else {
            label3.setText("");
            button1.setEnabled(true);
        }
    }//GEN-LAST:event_textField1TextValueChanged

    private void textField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textField1FocusLost
        // TODO add your handling code here:
        if (textField1.getText().equals("")) {
            label3.setText("*Empty field found");
            button1.setEnabled(false);
        } else {
            label3.setText("");
            button1.setEnabled(true);
        }
    }//GEN-LAST:event_textField1FocusLost

    private void button2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2ActionPerformed
        // TODO add your handling code here:
        textArea1.setText("");
    }//GEN-LAST:event_button2ActionPerformed

    private void checkbox1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox1ItemStateChanged
        // TODO add your handling code here:
        if (checkbox1.getState()) {
            textArea1.append("\nParent :\n " + file.getParent());
        }
    }//GEN-LAST:event_checkbox1ItemStateChanged

    private void checkbox2ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox2ItemStateChanged
        // TODO add your handling code here:
        if (checkbox2.getState()) {
            textArea1.append("\nSize :\n " + getFolderSize(file) + "bytes");
        }
    }//GEN-LAST:event_checkbox2ItemStateChanged
    public static long getFolderSize(File dir) {
        long size = 0;
        for (File file : dir.listFiles()) {
            if (file.isFile()) {
                // System.out.println(file.getName() + " " + file.length());
                size += file.length();
            } else {
                size += getFolderSize(file);
            }
        }
        return size;
    }
    private void checkbox3ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox3ItemStateChanged
        // TODO add your handling code here:
        if (checkbox3.getState()) {
            textArea1.append("\nLast Modified :\n " + new Date(WIDTH));
        }
    }//GEN-LAST:event_checkbox3ItemStateChanged

    private void checkbox4ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox4ItemStateChanged
        // TODO add your handling code here:
        if (checkbox4.getState()) {
            textArea1.append("\nIs Readable :\n " + file.canRead());
        }
    }//GEN-LAST:event_checkbox4ItemStateChanged

    private void checkbox6ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox6ItemStateChanged
        // TODO add your handling code here:
        if (checkbox6.getState()) {
            textArea1.append("\nIs Hidden :\n " + file.isHidden());
        }
    }//GEN-LAST:event_checkbox6ItemStateChanged

    private void checkbox5ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox5ItemStateChanged
        // TODO add your handling code here:
        if (checkbox5.getState()) {
            textArea1.append("\nIs Writable :\n " + file.canWrite());
        }
    }//GEN-LAST:event_checkbox5ItemStateChanged

    private void checkbox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox8ItemStateChanged
        // TODO add your handling code here:
        if (checkbox8.getState()) {

            textArea1.append("\n" + type + " is set to Readonly  :\n " + file.setReadOnly());
        } else {
            textArea1.append("\n" + type + " is not Readonly  :\n " + file.setWritable(false));
        }
    }//GEN-LAST:event_checkbox8ItemStateChanged

    private void checkbox9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox9ItemStateChanged
        // TODO add your handling code here:
        if (checkbox9.getState()) {
            if (file.exists()) {
                file.delete();
                textArea1.append("\n File  is has been deleted");
            } else {
                textArea1.append("\n File not found");
            }
        }
    }//GEN-LAST:event_checkbox9ItemStateChanged

    private void checkbox10ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkbox10ItemStateChanged
        // TODO add your handling code here:
        if (checkbox10.getState()) {
            textField2.setVisible(true);
            button3.setVisible(true);
        } else {
            textField2.setVisible(false);
            button3.setVisible(false);
        }
    }//GEN-LAST:event_checkbox10ItemStateChanged

    private void button3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button3ActionPerformed
        // TODO add your handling code here:
        File i = new File(URL);
        if (i.isFile()) {
            String a = "";
            int c = i.getName().lastIndexOf(".");
            if (--c >= 0) {
                a = i.getName().substring(c + 1);
            }
            File rename = new File(i.getParentFile(), textField2.getText() + a);
            if (i.renameTo(rename)) {
                textArea1.append("\n" + type + " is renamed to " + textField2.getText());
                textField2.setText("");
                textField2.setVisible(false);
                button3.setVisible(false);
                checkbox10.setState(false);
            }
        } else if (i.isDirectory()) {
            File rename = new File(i.getParentFile(), textField2.getText());
            if (i.renameTo(rename)) {
                textArea1.append("\n" + type + " is renamed to " + textField2.getText());
                textField2.setText("");
                textField2.setVisible(false);
                button3.setVisible(false);
                checkbox10.setState(false);
            }
        }
    }//GEN-LAST:event_button3ActionPerformed

    private void list1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_list1ItemStateChanged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_list1ItemStateChanged

    private void button5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button5ActionPerformed
        // TODO add your handling code here:

        String ext[] = list1.getSelectedItems();
        int arr[] = list1.getSelectedIndexes();
        int items = ext.length;

        if (list1.getSelectedIndex() == 6) {
            textField3.setVisible(true);
            label9.setVisible(true);
            if (!textField3.getText().equals("")) {
                if (file.isDirectory()) {
                    // File f10 = new File("D:\\java\\epta\\EPTA_Codes\\build\\classes");
                    if (file.exists()) {
                        String z[] = file.list(new SearchExtension(textField3.getText()));
                        if (z.length > 0) {
                            for (int i = 0; i < z.length; i++) {
                                textArea1.append("\n" + z[i]);
                            }
                        } else {
                            textArea1.append("\n No file found with '" + textField3.getText() + "' extension");
                        }

                    } else {
                        textArea1.append("\n not exist");
                    }
                } else if (file.isFile()) {
                    String extension = "";
                    int e = file.getName().lastIndexOf(".");
                    if (e > 0) {
                        extension = file.getName().substring(e + 1);
                    }
                    if (extension.equals(textField3.getText())) {
                        textArea1.append("\n File with extension '." + textField3.getText() + "'  is '" + file.getName() + "'");
                    } else {
                        textArea1.append("\n No file found with given extension '." + textField3.getText() + "'");
                    }

                }
            } else {
                textArea1.append("\n Please specify the extension");
                textArea1.append("\n for custom selection");
                textField3.requestFocus();
            }

        } else if (arr.length > 0) {

            for (int i = 0; i < arr.length; i++) {

                if (list1.getItem(arr[i]).equals("Custom")) {
                    textField3.setVisible(true);
                    label9.setVisible(true);

                    if (!textField3.getText().equals("")) {

                        String extension = "";
                        int e = textField3.getText().indexOf(".");
                        if (e >= 0) {
                            extension = textField3.getText().substring(e + 1);
                        } else {
                            extension = textField3.getText();
                            
                        }
                        String z[] = file.list(new SearchExtension(extension));
                        textArea1.append("\n Files with  extension  '" + extension + "' are:- ");
                        if (z.length > 0) {
                            for (int j = 0; j < z.length; j++) {
                                textArea1.append("\n \t" + z[j]);
                            }
                        } else {
                            textArea1.append("\n      No file found with '" + list1.getItem(arr[i]));
                        }
                        textArea1.append("\n");
                        continue;
                    } else {
                        textArea1.append("\n Please specify the extension");
                        textArea1.append("\n for custom selection");
                        textField3.requestFocus();
                    }
                } else {

                    String extension = "";
                    int e = list1.getItem(arr[i]).indexOf(".");
                    if (e >= 0) {
                        extension = list1.getItem(arr[i]).substring(e + 1);
                    }
                    String z[] = file.list(new SearchExtension(extension));
                    textArea1.append("\n Files with  extension  '" + extension + "' are:- ");
                    if (z.length > 0) {

                        for (int j = 0; j < z.length; j++) {
                            textArea1.append("\n \t" + z[j]);
                        }
                    } else {
                        textArea1.append("\n      No file found with '" + list1.getItem(arr[i]));
                    }
                    textArea1.append("\n");
                }
            }
        } else {
            textField3.setVisible(false);
            label9.setVisible(false);
        }
    }//GEN-LAST:event_button5ActionPerformed

    private void button4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button4ActionPerformed
        // TODO add your handling code here:
        for (int i = 0; i < 7; i++) {
            list1.deselect(i);
        }

    }//GEN-LAST:event_button4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new File_GUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private java.awt.Button button2;
    private java.awt.Button button3;
    private java.awt.Button button4;
    private java.awt.Button button5;
    private java.awt.Checkbox checkbox1;
    private java.awt.Checkbox checkbox10;
    private java.awt.Checkbox checkbox2;
    private java.awt.Checkbox checkbox3;
    private java.awt.Checkbox checkbox4;
    private java.awt.Checkbox checkbox5;
    private java.awt.Checkbox checkbox6;
    private java.awt.Checkbox checkbox8;
    private java.awt.Checkbox checkbox9;
    private java.awt.Label label1;
    private java.awt.Label label10;
    private java.awt.Label label2;
    private java.awt.Label label3;
    private java.awt.Label label4;
    private java.awt.Label label5;
    private java.awt.Label label6;
    private java.awt.Label label7;
    private java.awt.Label label8;
    private java.awt.Label label9;
    private java.awt.List list1;
    private java.awt.TextArea textArea1;
    private java.awt.TextField textField1;
    private java.awt.TextField textField2;
    private java.awt.TextField textField3;
    // End of variables declaration//GEN-END:variables

    private void enableContents(boolean a) {
        checkbox1.setEnabled(a);
        checkbox2.setEnabled(a);
        checkbox3.setEnabled(a);
        checkbox4.setEnabled(a);
        checkbox5.setEnabled(a);
        checkbox6.setEnabled(a);
        checkbox8.setEnabled(a);
        checkbox9.setEnabled(a);
        checkbox10.setEnabled(a);
        button4.setEnabled(a);
        button5.setEnabled(a);
        list1.setEnabled(a);

    }
}
